spring:
  datasource:
    url: jdbc:mysql://j11d110.p.ssafy.io:3415/DropzoneDB?serverTimezone=Asia/Seoul
    username: root
    password: dropzoned110
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafyd110@gmail.com
    password: qzvzxehofrkhhfat
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update  # 서버 환경에 맞게 테이블 검증
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL용 Hibernate Dialect 추가
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  # SQL 쿼리 로깅

  data:
    mongodb:
      uri: mongodb://mongodb_container:27017/DropzoneDB
      auto-index-creation: true

  thymeleaf:
    cache: false  # Thymeleaf 캐시 비활성화

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: ${JASYPT_KEY}
